###
# This is the configuration file for wscontrol
###

workstations.donald = [ 'enterprise' ]

workstations.parish = [ 
    'adam', 'alexis', 'anna', 'boyi', 'camryn', 
    'cooper', 'erica', 'evan', 'irene', 'justin',
    'kevin',  'michael', 'sarah', 'thais' 
    ]

workstations.provost = [
    'badenpowell', 'billieholiday', 'lesteryoung'
    ]

workstations.linux7 = [ 'cooper', 'thais', 'anna' ]
workstations.linux8 = [ 
    'adam', 'alexis', 'boyi', 'camryn', 'erica',
    'evan', 'irene', 'justin', 'kevin', 'michael',
    'sarah', 'enterprise' ]


