########################################################
# Section 1: Host definitions.
########################################################

ws.donald = [ 'enterprise' ]

ws.parish = [ 
    'adam', 'alexis', 'anna', 'boyi', 'camryn', 
    'cooper', 'erica', 'evan', 'irene', 'justin',
    'kevin',  'michael', 'sarah', 'thais' 
    ]

ws.provost = [
    'badenpowell', 'billieholiday', 'lesteryoung'
    ]

ws.all = [
    'adam', 'alexis', 'anna', 'boyi', 'camryn', 
    'cooper', 'erica', 'evan', 'irene', 'justin',
    'kevin',  'michael', 'sarah', 'thais', 
    'badenpowell', 'billieholiday', 'lesteryoung',
    'enterprise'
    ]

ws.nas = [ 'truenas', 'newnas', 'trueuser' ]

###
# Most of the parameters for connections are in the SSH
# config file. The SSH config file is robust and standard,
# so its use is preferred.
###

########################################################
# Section 2: executables
########################################################

exe.remote = "$(which ssh)"
exe.copy = "$(which scp)"


cmd.newuser = "useradd -m {username} -u $(id {userid} 2>/dev/null) && usermod -aG users {username}"
cmd.gpuinfo = "nvidia-smi --query-gpu=memory.total,memory.used,power.draw,fan.speed  --format=csv,noheader"
cmd.free = "{exe} -o ConnectTimeout={timeout} {target} free"
cmd.get_proc = "{exe} -o ConnectTimeout={timeout} {target} nproc"
cmd.in_use = "{exe} -o ConnectTimeout={timeout} {target} w"
cmd.remote_exec = "{exe} -o ConnectTimeout={timeout} {target} {cmd}"
cmd.copy2ws = "rsync --timeout={timeout} -av {dirname}/ {target}:{dirname}"
cmd.syncws = "rsync --timeout={timeout} -av --delete {dirname}/ {target}:{dirname}"

########################################################
# Section 3: SSH config info.
#
#  We include this configuration info with the project 
#  so that the required information about the network
#  is available within the program without regard to 
#  the user.
########################################################
ssh.configfile = $WSCONTROLHOME/sshconfig

