###
# This is the configuration file for wscontrol
###

########################################################
# Section 1: Host definitions.
########################################################

ws.donald = [ 'enterprise' ]

ws.parish = [ 
    'adam', 'alexis', 'anna', 'boyi', 'camryn', 
    'cooper', 'erica', 'evan', 'irene', 'justin',
    'kevin',  'michael', 'sarah', 'thais' 
    ]

ws.provost = [
    'badenpowell', 'billieholiday', 'lesteryoung'
    ]

ws.all = [
    'adam', 'alexis', 'anna', 'boyi', 'camryn', 
    'cooper', 'erica', 'evan', 'irene', 'justin',
    'kevin',  'michael', 'sarah', 'thais', 
    'badenpowell', 'billieholiday', 'lesteryoung',
    'enterprise'
    ]

ws.nas = [ 'truenas', 'newnas', 'trueuser' ]

###
# Most of the parameters for connections are in the SSH
# config file. The SSH config file is robust and standard,
# so its use is preferred.
###

########################################################
# Section 2: executables
########################################################

exe.remote = "$(which ssh)"
exe.copy = "$(which scp)"


cmd.newuser = "useradd -m {} -u $(id {} 2>/dev/null) && usermod -aG users {}"
cmd.gpuinfo = "nvidia-smi --query-gpu=memory.total,memory.used,power.draw,fan.speed  --format=csv,noheader"

